[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps"

# Настройка для функций Netlify, включая увеличенный таймаут
[functions]
  # Увеличиваем время выполнения до 30 секунд (максимум для функций Netlify)
  timeout = 30
  included_files = ["src/app/api/**"]
  node_bundler = "esbuild"
  external_node_modules = ["@deepgram/sdk", "openai", "node-fetch"]

# Перенаправления для API
[[redirects]]
  from = "/api/openai/*"
  to = "/.netlify/functions/openai-api/:splat"
  status = 200

[[redirects]]
  from = "/api/replicate/*"
  to = "/.netlify/functions/replicate-api/:splat"
  status = 200

# Настройки кэширования для улучшения производительности
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
