[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps"
  # Не указывайте здесь значения ключей API, они должны быть в настройках Netlify
  OPENAI_API_KEY = ""
  REPLICATE_API_TOKEN = ""

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@deepgram/sdk",
    "openai"
  ]
  included_files = ["src/app/api/**"]

# Исправленные перенаправления с более точным соответствием путей и правильным указанием параметров
[[redirects]]
  from = "/api/openai/chat"
  to = "/.netlify/functions/openai-api"
  status = 200
  force = true
  query = { path = "chat" }

[[redirects]]
  from = "/api/openai/generate-image"
  to = "/.netlify/functions/openai-api"
  status = 200
  force = true
  query = { path = "generate-image" }

[[redirects]]
  from = "/api/openai/text-to-speech"
  to = "/.netlify/functions/openai-api"
  status = 200
  force = true
  query = { path = "text-to-speech" }

[[redirects]]
  from = "/api/replicate/*"
  to = "/.netlify/functions/replicate-api/:splat"
  status = 200

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
